### ISSUE TITLE
Enhancement: Include variants of concern (Delte/Omicron) etc. in key on Genomics section

### ISSUE THREAD

**Issue by RowlandShaw** [russss/covidtracker#15]
For people stumbling on the data, think this could be more user friendly to include the code names for the variants of concern in the key; so "B.1.1" becomes "B.1.1 (inc. Omicron)" until B.1.1.529 triggers the greater than 15% for a week trigger.

Perhaps where a variant becomes dominant in it's own right could show as "B.1.1.529 (Omicron & variants) or "something"

**Comment by russss** [comment]
I had been meaning to re-visit this for a while, so I've just made a few improvements!
