### ISSUE TITLE
Scales need adjusting 

### ISSUE THREAD

**Issue by dsyme** [russss/covidtracker#18]
The scales on both the first two maps (incidence rate and change) need adjusting for omicron, currently the whole map is a sea pretty much all the same colour anywhere where omicron is prevalent

Thanks for this great resource!

**Comment by russss** [comment]
I just changed the scale on the incidence map earlier today! Try refreshing it.

Not sure if I'm going to do anything with the rate of change scale at this point. It's difficult because I'd like to plot the ratio on this map but it gets noisy when cases are low.
